version: '2'

services:
    mysql:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      container_name: mysql_practica_docred
      environment:
        MYSQL_DATABASE: 'practicadocred'
        MYSQL_USER: 'user_docred'
        MYSQL_PASSWORD: 'practicalDocred22#'
        MYSQL_ROOT_PASSWORD: 'practicalDocred22#'
      ports:
        - "3310:3306"
      expose:
        - '3310'
      volumes:
        - db_data:/var/lib/mysql
      restart: always
volumes:
  db_data: